config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'ideas#index'

  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, shallow: true, only: [:create, :destroy]
    
  end
  resources :users, only:[:new, :create]
  resource :session, only:[:new, :create, :destroy]
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    
    validates :title, presence: true, uniqueness: true
    validates :description, presence: true
    
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes,source: :user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    # =============CALLBACKS=====================
    before_action :find_idea, only: [:edit, :update, :show, :destroy]
    before_action :authenticated_user!, except: [:index, :show]
    before_action :authorize_user!, only:[:edit, :update, :destroy]
    # ==============CREATE========================
    def new
        @idea = Idea.new
    end

    def create
        @idea = Idea.new(idea_params)
        if current_user
            @idea.user = current_user
            if @idea.save
                flash[:notice]= "Idea created successfully!"
                redirect_to idea_path(@idea)
            else
                render :new, status: 303  
            end
        else
            redirect_to root_path
        end
       
        
    end
    # ================READ========================
    def index
        @ideas = Idea.order(created_at: :desc)

    end

    def show
        @reviews = @idea.reviews.order(created_at: :desc)
        @review = Review.new
        @like = @idea.likes.find_by(user: current_user)
    end
    # ===============UPDATE==========================
    def edit

    end

    def update
        if @idea.update(idea_params)
            redirect_to idea_path(@idea)
          else
            render :edit
          end
    end
    # ================DELETE=========================
    def destroy
        @idea.destroy
        flash[:danger] = "Idea has been deleted!"
        redirect_to root_path
    end

    private

    def authorize_user!
        redirect_to root_path, alert: "Not authorized" unless can?(:crud, @idea)
    end

    def find_idea
        @idea = Idea.find params[:id]
    end

    def idea_params
        params.require(:idea).permit(:title, :description)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/edit.html.erb
<div class="container">

<%= form_with(model: @idea) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :description %>
    <br>
    <%= form.text_area :description, cols:50, rows: 5, class: "form-control"%>
  </div>
<br>

<%= form.submit "Update Idea", class: "btn btn-outline-dark" %>
<% end %>
</div>

app/views/ideas/index.html.erb
<div class="container">
<div class="container d-flex flex-wrap justify-content-around">
<% @ideas.each do |idea| %>
  <div class="container">

    <h5 class="card-title"><%= link_to idea.title, idea_path(idea), class: "text-decoration-none text-dark"%></h5>
    <p class="card-text"><%=idea.description%></p>

    <div class="container m-0 p-0 d-flex flex-row">
    <div class="container m-0 p-0 d-flex flex-row">
    <small class="text-dark mt-1 me-2" style="text-decoration: underline">By <%= idea.user.first_name %></small>
    <small>
    <% if idea.user != current_user%>
    <% like = idea.likes.find_by(user: current_user)%>
    <% if current_user && like.present? %>
    <div><%= button_to "Liked", like_path(like), method: :delete , class:"btn btn-outline-dark btn-sm" %></div>
    <% elsif current_user %>
    <div>
   <%= button_to 'Like', idea_likes_path(idea), method: :post , class:"btn btn-outline-dark btn-sm" %>
    </div>
    <% end %>
    <% end %>
    </small>
    </div>
    <small style="width: 5em">Likes: <%= idea.likes.count %></small>
    </div>
    <hr>
</div>
<% end %>
</div>
</div>

app/views/ideas/new.html.erb
<div class="container d-flex justify-content-center">
<div class="col-sm-6 m-4">
<%= form_with(model: @idea) do |form| %>
<% if @idea.errors.any? %>
  <p><%= @idea.errors.full_messages.join(', ') %> </p>
<% end %>
  <div class="form-group">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :description %>
    <br>
    <%= form.text_area :description, cols:50, rows: 5, class: "form-control"%>
  </div>
<br>

  <%= form.submit "Create Idea", class: "btn btn-outline-dark" %>
 <% end %>
</div>

app/views/ideas/show.html.erb
<div class="container d-flex justify-content-center">
<div class="container">
<div class="container" style="margin: 1em">
  <h1><%= @idea.title %></h2>
  <p><%= @idea.description %></p>
  <small>Posted <%= time_ago_in_words(@idea.created_at) %> ago</small><br>
  <small>By <%= @idea.user.full_name %></small>
  <br>
  <div class="container d-flex p-0">
  <small class="mt-2 me-1">Likes: <%= @idea.likes.count %></small>
  <% if @idea.user != current_user%>
  <small>
  <% if current_user && @like.present? %>
  <div><%= button_to "Liked", like_path(@like), method: :delete , class:"btn btn-outline-dark btn-sm" %></div>
  <% elsif current_user %>
  <div>
   <div><%= button_to 'Like', idea_likes_path(@idea), method: :post , class:"btn btn-outline-dark btn-sm" %></div>
  </div>
  <% end %>
  </small>
  <% end %>
  </div>
  <br>

  <%# Edit and Delete Buttons %>
  <% if can? :crud, @idea %>
  <div class="btn-group">
  <%= link_to 'Edit', edit_idea_path(@idea), class: "btn btn-outline-dark me-2 rounded", style: "" %>
  </br>
  <%= button_to 'Delete', idea_path(@idea), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-outline-dark"  %>  
  </div>
  <% end %>


</div>


<div class="container" style="margin: 1em">
<h3>Reviews</h3>

<% if @review.errors.any? %>
  <ul>
    <%  @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model:[@idea, @review]) do |f| %>
  <div class="form-group">
    <%= f.text_area :body, cols: 20, rows: 2, placeholder: "What's on your mind?", class:"form-control", style:"width: 32em" %>
  </div>
  <br>
  <%= f.submit "Submit", class: "btn btn-outline-dark" %>
<% end %>
</div>
<div class="container" style="margin: 1em">
<% @reviews.each do |review| %>
  <div class="mb-3">
    <%= review.body %><br>
    
    <span style="display: flex; flex-direction: row; align-items: baseline"><small>Reviewed <%= time_ago_in_words(review.created_at) %> ago by <%= review.user.full_name %></small>
    <%# Delete Button %>
    <% if can? :crud, review %>
    <span><%= button_to "Delete", idea_review_path(@idea, review), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "btn btn-outline-dark btn-sm mx-2", style:"text-decoration: none; box-shadow:none" %></span></span>
    <% else %>
    <br>
    <% end %>
    
  </div>
<% end %>
</div>

</div>
</div>